#!/usr/bin/env bash
# Script that configures a new Ubuntu machine

sudo apt-get update -y
# Install nginx
sudo apt-get -y install nginx
# Allow nginx access
sudo ufw allow 'Nginx HTTP'
# Display hello world upon a GET request
echo "Hello World!" | sudo tee /var/www/html/index.html

# Check if Nginx is already running
if [ "$(service nginx status | grep 'active')" ]; then
    # Reload Nginx configuration
    sudo service nginx reload
else
    # Start Nginx
    sudo service nginx start
fi
