#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update
# Install nginx
sudo apt-get install -y nginx
# Allow nginx access
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/x.com\/0xTobii permanent;"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-available/default

# You can also use the below if you like stress :p
# printf %s "server {
#     listen 80;
#     listen [::]:80 default_server;
#     root   /var/www/html;
#     index  index.html index.htm;

#     server_name _;

#     location /redirect_me {
#         return 301 http://x.com/0xTobii;
#     }
# }" > /etc/nginx/sites-available/default

sudo service nginx restart
