#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://x.com/0xTobii;
    }
}" > /etc/nginx/sites-enabled/default

sudo service nginx restart