#!/usr/bin/env bash
# Configures Nginx server to have a custom 404 page that contains the string 
# -- Ceci n'est pas une page.

sudo apt-get update -y
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/x.com\/0xTobii permanent;"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-enabled/default

replacement="server_name _;\n\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-enabled/default

# printf %s "server {
#     listen 80;
#     listen [::]:80 default_server;
#     root   /var/www/html;
#     index  index.html index.htm index.nginx-debian.html;

#     server_name _;

#     location /redirect_me {
#         return 301 http://x.com/0xTobii;
#     }

# 	error_page 404 /404.html;
#     location /404 {
#       root /var/www/html;
#       internal;
#     }
# }" > /etc/nginx/sites-available/default
sudo service nginx restart
