#!/usr/bin/env bash
sudo apt-get update
# Install nginx
sudo apt-get -y install nginx
# Allow nginx access
sudo ufw allow 'Nginx HTTP'
# Display hello world upon a GET request
echo "Hello World!" | sudo tee /var/www/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html index.htm;

    location / {
        add_header X-Served-By $hostname
    }
}" > /etc/nginx/sites-available/default

# Check if Nginx is already running
if [ "$(service nginx status | grep 'active')" ]; then
    # Reload Nginx configuration
    sudo service nginx reload
else
    # Start Nginx
    sudo service nginx start
fi