#!/usr/bin/env bash
# Script that configures a new Ubuntu machine
sudo apt-get update -y
# Install nginx
sudo apt-get -y install nginx
# Allow nginx access
sudo ufw allow 'Nginx HTTP'
# Display hello world upon a GET request
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
# Restart nginx to apply changes
# sudo service nginx reload
sudo service nginx restart
# Check if Nginx is already running
# if [ "$(service nginx status | grep 'active')" ]; then
#     # Reload Nginx configuration
#     sudo service nginx restart
# else
#     # Start Nginx
#     sudo service nginx start
# fi
# apt-get update
# apt-get -y install nginx
# ufw allow 'Nginx HTTP'
# echo "Hello World!" > /var/www/html/index.html
# service nginx start
