#!/usr/bin/env bash
# Script that configures a new Ubuntu machine
sudo apt-get update -y
# Install nginx
sudo apt-get -y install nginx
# Allow nginx access
sudo ufw allow 'Nginx HTTP'
# Display hello world upon a GET request
sudo sh -c echo "Hello World!" > /var/www/html/index.nginx-debian.html
# Restart nginx to apply changes
# sudo service nginx reload
sudo service nginx restart
