#!/usr/bin/env bash
# Install and configure HAproxy on a load balancer server

# sudo apt-get -y update
# sudo apt-get -y install haproxy

# server_config=\
# "
# frontend tobii-frontend
#         bind *:80
#         mode http
#         default_backend tobii-backend
# backend tobii-backend
#         balance roundrobin
#         server 284283-web-01 204.236.240.195:80 check
#         server 284283-web-02 52.91.123.82:80 check
# "

# echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
# echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
# sudo service haproxy restart


apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 284283-web-01 204.236.240.195:80 check
    server 284283-web-02 52.91.123.82:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start