#!/usr/bin/env bash
# Install and configure HAproxy on a load balancer server

sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend  tobii-frontend
        bind *:80
        mode http
        default_backend tobii-backend
backend tobii-backend
        balance roundrobin
        server 284283-web-01 204.236.240.195:80 check
        server 284283-web-02 52.91.123.82:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart