#!/usr/bin/env bash
# Displays the content of the current directory in a list format
#   Where only the part of the name after the first dash is displayed.

for file in *
do
    if [ "${file:0:1}" != "."  ]; then
        echo "$file" | cut -d '-' -f 2-
    fi
done
