#!/usr/bin/env bash
# Script that runs Nginx as user 'nginx'

sudo apt-get -y update
sudo apt-get -y install nginx
# Change the user in the nginx configuration
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
# Update the listening port in a server block
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
# Restart Nginx
sudo service nginx restart
