#!/usr/bin/env bash
# Script that runs Nginx as user 'nginx'

sudo service nginx stop
# Change the user in the nginx configuration
echo "user nginx;" >>/etc/nginx/nginx.conf
# sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
# Update the listening port in a server block
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
# File permissions for nginx.conf
chmod 644 /etc/nginx/nginx.conf
# Kill apache as it may interfere with nginx
pkill apache2
# Restart Nginx
sudo -u nginx service nginx start
